language: rust
sudo: false
dist: trusty

cache:
  cargo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: 1.40.0
    - rust: nightly

before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      rustup component add rustfmt
      rustup component add clippy
    fi

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      cargo fmt -- --check
      cargo clippy --all-targets --all-features -- -D warnings
    fi
  - cargo test --all-features --all -- --nocapture
